### ISSUE TITLE
앱의 실행 과정을 단순화합니다.

### ISSUE THREAD

**Issue by limgit** [binarysound/random-poll#11]
## Problem
작성한 코드를 테스트하기 위해 docker를 실행하려면 긴 명령어를 입력해야 합니다. 이부분을 부분적으로 자동화하고자 합니다.

## Suggested Solution
두 가지 해결 방안을 생각해봤습니다.
1. run.sh 파일을 작성하여 이를 통해 실행
2. manage.py 파일에 실행 로직을 기록해서 이를 통해 실행 ([subprocess.run](https://stackoverflow.com/a/4760517)을 이용할 수 있습니다.)

**Comment by JeongHoJeong** [comment]
유지보수성이 떨어지고 portability가 낮은 쉘 스크립트는 가능한 지양하고 `manage.py`로 전부 해결하면 어떨까 합니다.

**Comment by limgit** [comment]
음 그러면 최종적으로 `$ python manage.py run`의 명령을 돌리면 `$ docker blah`가 실행되어서 docker가 열리고 웹 서버가 돌아가는 형태면 괜찮을까요? manage.py에 추가될 기능은 차차 생각하도록 하고

**Comment by JeongHoJeong** [comment]
### 기대하는 기능들
```bash
python manage.py --help    # 혹은 -h, 가능한 명령 집합 출력
python manage.py run-db    # DB 컨테이너를 띄움
python manage.py init-db   # DB 초기화 작업
python manage.py run       # 서버 실행
```

명령어의 이름이 고민되긴 합니다만, 최소한 이 수준의 명령셋까지만 동작해도 좋을 것 같습니다.

**Comment by JeongHoJeong** [comment]
생각해보니 이러면 실행 환경의 python version에 dependent한 개발이 되기도 하겠네요. 쉘 스크립트로만 짜면 의존성이 Docker에만 존재하니.. portability 측면에선 오히려 쉘 스크립트가 나을 수도 있을 것 같습니다.

**Comment by limgit** [comment]
그러면 쉘 스크립트로 작성한 뒤에 이를 `manage.py`에서 참조하는 식으로 만들면.... 너무 중복 작업이 많으려나요 😭

**Comment by JeongHoJeong** [comment]
궁극적으로는 실행 환경에 Docker만 깔려 있으면 앱이 돌았으면 좋긴 하겠는데요. 쉘 스크립트를 얇게 짜서 연결점으로만 두고, 실제 management 작업은 Docker 컨테이너 내부에서 이루어지도록 하는 것도 방법일 것 같습니다. 이렇게 하면 python 코드를 쓰더라도 컨테이너 내부에서 돌게 할 수 있을테니까요.

**Comment by limgit** [comment]
그럼 shell script는
 - DB container 띄우기
 - App container 띄우기

까지만 관여하고, 이후에 사용자가 app container 내부에서 `manage.py`를 이용해 db 초기화를 하거나 서버를 구동하는 등의 작업을 할 수 있는 형태가 되는 건가요?

**Comment by JeongHoJeong** [comment]
@limgit 음.. 사용자가 쉘 접속을 통한 작업을 굳이 하지 않아도 되면 좋겠어서요. 그리고 컨테이너 외부에서 돌아야 하는 부분들이 많아서 조금 머리가 아프네요. 자동화 되어야 하는 부분들은 다음과 같습니다.

### DB 실행
1. config 파일의 내용에 맞게 DB 정보를 획득
2. 위에서 얻은 DB 정보를 바탕으로 `docker run`

### App 실행
1. config 파일의 내용에 맞게 DB 접속 정보 일부(password, database)를 획득
2. `docker network inspect bridge`의 결과를 JSON parsing하여 DB container의 IP 획득
3. 위 내용을 바탕으로 접속

### DB의 초기화
1. `docker run`시 환경 변수 여부에 따라 한꺼번에 처리하거나, (이상적)
2. 컨테이너에 쉘 접속 후 관리용 python script를 실행해 처리

작성 난이도를 생각해볼 때 python script가 가장 현실적인 것 같기도 한데요... 개발 환경에 Docker 뿐 아니라 python까지 requisite로 두게 되는 점이 마음에 걸립니다. 별 문제 없을 것 같기도 하면서도 좀 걸리네요. 😟

**Comment by JeongHoJeong** [comment]
App 실행의 2번을 어떻게 container 내부에서 알 방법만 있으면 좀 더 문제가 쉬워질 것 같기도 하네요. 어떻게 잘 하면 될 것 같기도 한데요.

**컨테이너 밖에서 해야만 하는 일**들을 **컨테이너 안쪽에서 할 수 있는 일**들로 옮길 수만 있으면 됩니다.

**Comment by JeongHoJeong** [comment]
이러면 DB용 Dockerfile과 App용 Dockerfile을 구분할 필요가 있겠네요.

- [Multiple Dockerfiles in project](https://stackoverflow.com/a/32108873)
- [Best practices for writing Dockerfiles](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/)

[Docker Hub](https://hub.docker.com/)를 활용하는 것도 방법일 것 같긴 한데요... 이 부분도 역시나 고민.

**Comment by JeongHoJeong** [comment]
@limgit #15 가 해결되었으니 이건 닫아도 될까요?

**Comment by limgit** [comment]
아 이쪽에도 연결되어 있었군요. DB 초기화 자동화가 아직 완료되지는 않았지만 그건 이슈가 따로 열려있으니 이건 닫도록 하겠습니다.
