### ISSUE TITLE
Issue Template을 작성합니다.

### ISSUE THREAD

**Issue by limgit** [binarysound/random-poll#12]
## Problem
이슈 작성하면서 느낀건데 PR과 마찬가지로 이슈에도 적당한 템플릿이 있으면 좋을 것 같습니다.

## Suggested Solution
지금 제가 작성하고 있는 이 이슈와 같은 형식의 템플릿이면 충분할 것 같습니다.

## Comments
혹시 더 필요한게 있거나, 굳이 이슈는 템플릿이 필요 없을거 같다 하시면 의견 남겨주세요. @JeongHoJeong

**Comment by limgit** [comment]
헤더 중 **Problem**을 다른 이름으로 바꾸고 싶은데 마땅한 단어가 떠오르지 않네요. "문제 제시" 내지는 "개선이 필요한 부분"을 뜻하는 다른 단어가 있으면 좋을것 같은데..

**Comment by JeongHoJeong** [comment]
좋은 의견입니다. 사실 한글로 하는 것도 방법이긴 하죠. 😁 
**Problem** 대신 **Issue**는 어떤가요?

**Comment by limgit** [comment]
음 그것도 괜찮을것 같네요 Issue 안에 Issue라 뭔가 묘한 느낌은 있지만 😸

**Comment by JeongHoJeong** [comment]
@limgit 완료된 이슈이니 닫아주셔도 되겠습니다.

**Comment by limgit** [comment]
깜빡했군요 😢
