### ISSUE TITLE
Docker Compose를 적용합니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/random-poll#15]
## Issue
Multi-container Docker application이다보니 효율적인 관리의 니즈가 아주 높습니다. #11 과 연관이 큽니다.

## Suggested Solution
[Docker Compose](https://docs.docker.com/compose/overview/)를 적용해 DB container와 App container간의 연결을 체계적으로 관리합니다.

## Comment
역시 필요하다 싶은 건 이미 다 있네요.

**Comment by limgit** [comment]
@JeongHoJeong 했다! 머지! 닫는다! 이슈!
