### ISSUE TITLE
dev.cfg와 .env를 통합합니다.

### ISSUE THREAD

**Issue by limgit** [binarysound/random-poll#18]
## Issue
현재 `dev.cfg`와 `.env`의 내용이 겹치는 부분이 많이 있습니다. 특히 password의 경우, 양 파일에서 동일한 값을 갖도록 해야하는데 consistency 문제가 발생할 수도 있습니다.

## Suggested Solution
 - `dev.cfg`의 내용을 `.env` 안으로 통합합니다.

## Comment
 - server port, db password, db port는 `.env`안에 기술되지만 server host ip 등의 정보를 어떻게 할지 결정해야 합니다.

**Comment by limgit** [comment]
단순히 `dev.cfg`의 내용을 `.env`로 합쳐 넣고, `main.py`에서 `dev.cfg` 대신 `.env`를 참조하게 하는거면 충분할까요? app의 host 주소나 이런 부분은 application-specific한 내용이라 막상 `.env`에 넣자니 조금 모양새가 이상해보이기는 하네요 @JeongHoJeong

**Comment by JeongHoJeong** [comment]
어차피 모두 Docker로 도는 이상 기존의 `dev.cfg` 내부의 `[app]` 섹션은 아예 빼도 될 것 같습니다. 사실 실행자가 설정해야 하는 부분이 현재의 `.env`에 모두 들어있으니, `main.py`에서 `dev.cfg`를 읽는 부분을 빼고 `.env`만을 읽게 하면 될 것 같습니다.

**Comment by JeongHoJeong** [comment]
작업시 필요하시면 다음 링크 참조하시면 될 것 같아요!

https://docs.docker.com/compose/env-file/#syntax-rules
