### ISSUE TITLE
Docker를 적용합니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/random-poll#4]
## [Docker](https://www.docker.com/)
개발과 배포는 신속하고 정확하게 이루어져야 합니다. Docker는 구세주입니다.

## 현재 솔루션 아이디어
- `python:3.6-slim`을 base로 이미지를 만듭니다.
- `--volume` 옵션으로 PWD를 `/src`에 mount하고 이 부분을 container에서 실행하여 개발과 동시에 테스트를 할 수 있는 환경을 마련합니다.

### 데이터베이스 연결
- container 내부에 바로 설치하는 것도 방법이고, 혹은 호스트 머신의 DB와 직접 연결하는 방법을 생각할 수도 있습니다. 마침 [Docker 공식 문서](https://docs.docker.com/engine/examples/postgresql_service/)에 PostgreSQL을 dockerize하는 방법이 잘 설명되어 있네요.
- [How to deal with persistent storage in Docker](https://stackoverflow.com/questions/18496940/how-to-deal-with-persistent-storage-e-g-databases-in-docker): 같은 궁금증의 StackOverflow 질문입니다.

**Comment by limgit** [comment]
저는 Docker 사용해본 적이 없으니 이부분은 일단 맡기고...
1. PWD가 뭔가요?
2. 만약 container 내부에 바로 db를 설치하게 되면 db에 변경이 생길 때마다 git에서 이를 추적하게 되나요? 그렇지 않으면 container 내부에 db를 설치하는 쪽도 괜찮을 것 같습니다.

\+ docker를 사용하게 되면 pyenv virtualenv는 필요없어지게 되는거 맞나요? 이해하고 있는게 맞나 헷갈리네요 😭

**Comment by JeongHoJeong** [comment]
@limgit 
1. [pwd](https://en.wikipedia.org/wiki/Pwd): working directory를 이야기하고자 이렇게 썼습니다.
2. DB 변경 이력은 migration tool인 Alembic 등으로 관리할 예정이니 Git에 모두 저장됩니다.
3. 네, 일단 적어도 실행에 있어서는 Docker만 필요합니다. (물론 IDE에서의 pylint 등의 지원을 받으려면 어느 정도 개발 환경에서도 세팅을 하면 편하긴 하겠죠) 컨테이너 내부 관리를 어떻게 하겠느냐에 따라 달라지긴 하겠지만, 한 컨테이너에 여러 파이썬 버전을 쓸 일은 없겠죠?

**Comment by limgit** [comment]
아 print였군요 p가. 저는 현재 작업 디렉토리는 cwd (current working directory) 로 쓰는게 습관이라 헷갈렸네요. 제가 얘기한 db 변경 이력은 스키마나 이런 부분이 아니고 실제 저장된 데이터가 변경되거나 하는 부분을 이야기한 건데 이건 마이그레이션 툴에서 관리하지 않지 않나요? 2번 질문을 좀더 clarify하면 container 내에 db 를 설치하고 사용하게 되면, db의 content가 변경되었을 때, 이것이 docker file도 변경하게 되어 git에 의해 추적되게 되느냐는 것이었습니다.

**Comment by limgit** [comment]
죄송합니다 😢 mobile github의 close and comment 버튼이 굉장히 누르기 쉬운 위치에 있었네요 😭

**Comment by JeongHoJeong** [comment]
@limgit 아 그 부분 말씀이셨군요. 스키마와 연관 없는 부분은 `Dockerfile`과는 무관한 부분이라 걱정 안 하셔도 됩니다.

**Comment by limgit** [comment]
@JeongHoJeong 그러면.... 그냥 container 내부에 db를 설치하는 쪽이 consistency 면에서 더 낫지 않나요? 굳이 호스트 머신의 DB와 연동할 필요성은...

**Comment by JeongHoJeong** [comment]
@limgit 그럼 container를 지울 때마다 DB도 함께 다 날아갑니다. 단순한 격리에 대한 cons치곤 좀 큰 편이죠.

**Comment by limgit** [comment]
@JeongHoJeong 음 제가 아직 Docker에 대한 이해가 제대로 되지 않았나보네요. 일단 제가 [Documentation](https://docs.docker.com/)을 빠르게 읽고 와서(...) 마저 이야기하겠습니다.

**Comment by limgit** [comment]
넵 대충 Docker의 기본 작동 방식이 clarify된 것 같네요. 일단 개발중일때는 컨테이너를 디비와 앱 따로 나눠 돌려서 하는 것도 괜찮을것 같습니다.

**Comment by JeongHoJeong** [comment]
@limgit 방법을 어느 정도 찾은 것 같습니다. PostgreSQL 용 container를 띄워 접속하는 방법입니다.

```bash
cd /some/path/to/random-poll
docker pull postgres
docker run --name rp-postgres -e POSTGRES_PASSWORD=mysecret -d postgres
```

위까지 실행한 후, 다음 명령을 실행해 `rp-postgres` 컨테이너의 IP를 확인해 `dev.cfg`에 적어 넣습니다.

```bash
docker network inspect bridge
```

이제 앱 컨테이너를 띄웁니다. 물론 그 전에 `Dockerfile`이 필요하고, `docker build`로 `randompoll` 이미지를 만드는 작업이 선행되어야 합니다. 80은 컨테이너의 포트이고, 7654는 그에 연결할 로컬 머신의 실제 포트입니다.

```bash
docker run -it --rm -v `pwd`:/src -p 7654:80 randompoll
```

이제 DB와 연결된 앱 컨테이너를 사용할 수 있습니다!

좀 더 디테일한 정보가 필요하다면 [제 Evernote 노트](https://www.evernote.com/l/APJdV94drpZFepUpk0jcffdDHj8XWg1Yqx4)를 참고해주세요.
