### ISSUE TITLE
Pull request template을 작성합니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/random-poll#5]
### [Issue and Pull Requests templates](https://github.com/blog/2111-issue-and-pull-request-templates)
`.github/PULL_REQUEST_TEMPLATE.md` 파일을 작성해 넣습니다.

### [How to write the perfect pull reqeust](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)
그렇다면 어떤 것이 좋은 pull request일까요? 바로 위 글을 참고하면 될 것 같습니다.

**Comment by limgit** [comment]
오 이런것도 있네 :+1:
