### ISSUE TITLE
config file example을 작성합니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/random-poll#7]
현재 config file은 `dev.cfg`라는 이름으로 연결이 되어 있습니다만, 로컬 세팅마다 다를 것이기에 `.gitignore`되어 있습니다. 단, 예시 파일이 필요하기에 관리가 필요합니다.

Wiki도 방법이지만, 프로젝트 내부에 `docs`라는 디렉토리를 만들어 그 밑에 파일로 포함시키는 것도 좋을 것 같습니다. 어떻게 생각하세요? @limgit

**Comment by limgit** [comment]
어... 어느쪽이든 괜찮을 것 같네요. docs로 관리하게 되면 github independent 하게 되니 조금 더 나을거 같기도 하구요. 그러면 `config_file_template.cfg` 내에
```cfg
database:
  - user: <Username>
  - password: <Password>
```
같은 식으로 파일을 기록해두는건가요?

**Comment by JeongHoJeong** [comment]
@limgit 아 아뇨. `docs` 자체도 Git에 포함해 버전 컨트롤하려 합니다. 그래야 특정 시점에 config가 어땠는지 바로 파악할 수 있을테니까요.

기록 양식은 실제 `dev.cfg`[(INI 포맷)](https://en.wikipedia.org/wiki/INI_file)와 거의 동일하게 하되, environment dependent한 부분만 빈칸으로 뚫어둘 예정입니다.

**Comment by limgit** [comment]
@JeongHoJeong 음 제가 얘기한게 딱 그 얘기였는데 전달이 미흡했나보네요 😭

**Comment by JeongHoJeong** [comment]
@limgit 아 github independent하단 의미를 잘못 이해했네요. 미안합니다 😢 
그럼 일단 동의가 된 걸까요?

**Comment by limgit** [comment]
@JeongHoJeong git independent랑 헷갈리셨나보네요 😸 넵 example 작성해서 PR 넣어주시면 확인해보도록 하겠습니다!
