### ISSUE TITLE
프로젝트 구조를 결정합니다.

### ISSUE THREAD

**Issue by limgit** [binarysound/random-poll#8]
이 이슈에서는 프로젝트의 디렉토리 구조, 코드 스타일링 등에 관한 기본적인 사항을 결정합니다. 아래는 간단히 생각해본 각 항목에 대한 내용인데, 더 나은 디렉토리 명이 있다든가 하는 경우 코멘트 부탁드립니다.

### 디렉토리 구조
 - `./app/`: Application code
   - `./main.py`: 응용프로그램의 진입점. `./main.py <arguments>`만으로 웹 서버가 실행되면 될 것 같습니다.
   - `./static/`: Web page에 사용될 static files (js / css 등) directory. 아직 `Vue.js`에 대한 이해가 없는 관계로 이부분을 정확히 어떻게 해야 할지 모르겠네요. 
   - `./user_module_1/`: 기능의 단위는 모듈로 분리해내고 참조하는게 맞을 것 같습니다.
 - `./docs/`: 기타 project-level static files (document, configs)
 - `./tests/`: 테스팅 코드. 필요에 따라 내부에 `/test_user_module_1/` 하는 식으로 모듈별 테스팅 코드를 분리해 넣으면 될 것 같습니다. 이 디렉토리 내부의 모든 디렉토리와 파일은 `test_*`의 파일 이름 형식을 가집니다. `test_full.py` 파일을 통해 모든 테스트를 한번에 실행해주는 것도 괜찮을 것 같네요.
 - `./manage.py`: App 전체에 대한 관리를 하는 파일입니다. 앱의 실행과 종료 등은 모두 이 파일을 통해서 이루어질 수 있습니다.
 - `./requirements.txt`: pip requirements
 - `./README.md`
 - 기타 파일

### 코드 스타일
[autopep8](https://pypi.python.org/pypi/autopep8)나 [pylint](https://www.pylint.org/)의 적용을 생각하고 있습니다. + [type hint](https://docs.python.org/3/library/typing.html)의 사용도 좋을 것 같습니다.

@JeongHoJeong

**Comment by JeongHoJeong** [comment]
👍이지만 질문이 몇 개 있습니다.

1. 모듈을 최상단에 expose하는게 맞을까요? 모듈 개수가 점점 늘어날수록 최상단 디렉토리가 복잡해질 것 같은 불안감이 있네요.
2. app code들은 모두 `./app/` 밑에 넣고, `main.py`도 그 안으로 넣으면 어떨까요? 대신 `manage.py`를 최상단에 두어 각종 명령을 다 캡슐화하면 어떨까요?

**Comment by limgit** [comment]
그 부분이 고민되어서 `./src/` 밑으로 app code를 넣는걸 생각했는데 역시 이쪽이 나을거 같네요. 그럼 `./src/`밑으로 `./main.py`, `./static/`, `./user_module/`을 넣는 걸로 합시다. 혹시 `./src/` 보다 `./app/`이 좋거나, 다른 더 넣을게 있으면 말씀해주세요. 😄

`manage.py` 아이디어도 괜찮은 것 같습니다.

@JeongHoJeong

**Comment by JeongHoJeong** [comment]
그 부분을 제외하더라도 다른 부분도 source인 점이 분명히 있고, application code임을 명시한다는 점에서 개인적으론`./app/`이 더 끌리네요. 다른 부분엔 저도 동의합니다. 😃

**Comment by limgit** [comment]
이슈 원문 Revise 했습니다. 확인하고 피드백 주세요.

autopep8과 pylint중엔 어느쪽이 나을까요? autopep8은 정말 단순히 code formatting과 관련된 툴인것 같고, pylint는 static analysis까지 겸해주어서 후자가 더 나아보이긴 하는데, configuration에 시간이 좀 들것 같습니다. type hint는 반드시 사용하는 것이 좋아 보이구요.

@JeongHoJeong

**Comment by JeongHoJeong** [comment]
구조는 깔끔해 보입니다. 👍

빌드 툴에 대해서는 어떻게 생각하시나요? (pyc의 사용 등)

static analysis가 포함된다면 configuration에 시간이 들더라도 pylint 쪽이 더 나을 것 같습니다. type hint도 좋은 아이디어같네요.

**Comment by limgit** [comment]
음... 빌드 툴이라는게 어떤걸 의미하는건가요?
@JeongHoJeong

**Comment by JeongHoJeong** [comment]
@limgit 파이썬 컴파일을 염두에 두고 한 이야기긴 했는데 당장은 먼 이야기인 것 같기도 하네요. 크게 신경 안 쓰셔도 될 것 같습니다.

**Comment by limgit** [comment]
디렉토리 재구성을 지금 시점에서 하는게 나을까요? 지금 할거라고 해봐야 main.py를 ./app/ 안으로 보내고 그에 맞게 Dockerfile을 수정하는 일 정도 뿐입니다만

**Comment by JeongHoJeong** [comment]
@limgit 미리 뼈대를 잘 잡아두고 가지 않으면 나중에 후회할 것 같아서요. 다만 이 이슈에 대한 작업 자체는 약간 늦게 들어가야 할 것 같습니다. 일단 Docker를 통한 app development & deploy에 대한 논의부터 정확히 끝낸 후 이 이슈를 처리하러 와야 할 것 같습니다.

**Comment by JeongHoJeong** [comment]
@limgit 개발 환경에 대한 논의가 어느정도 마무리되었으니 이제 이 이슈를 처리해야 할 것 같습니다. 다른 이슈들이 전부 여기로 얽혀 있어서 이걸 먼저 처리하지 않고는 다른 일이 힘들 것 같습니다.

**Comment by limgit** [comment]
@JeongHoJeong `.env` 파일은 프로젝트 루트에 둬야 하겠죠?

**Comment by JeongHoJeong** [comment]
@limgit 넵, 그게 좋겠습니다.

**Comment by limgit** [comment]
#25 에서 디렉토리 구조 설정은 마쳤고, 코드 스타일링 툴은 #19 이슈에서 다루고 있으니 이 이슈는 닫아도 괜찮을까요? @JeongHoJeong

**Comment by JeongHoJeong** [comment]
@limgit 많이 자리가 잡혔으니 닫아도 될 것 같습니다.
